- README.md
- mapchete/config_utils.py
- test/tests.py
> Segmentize footprints

- mapchete/config_utils.py
- mapchete/io_utils.py
- mapchete/mapchete.py
* read & reproject vector data
* write GeoJSON files
closing #10
> Geojson rw

- cli/mapchete_execute.py
- doc/configuration.md
- doc/installation.md
- mapchete/__init__.py
- mapchete/config_utils.py
- mapchete/formats.py
- mapchete/io_utils.py
- mapchete/mapchete.py
- mapchete/numpy_io.py
- setup.py
- test/example_process.py
- test/testdata/numpy.mapchete
- test/tests.py
add numpy read & write option to store multidimensional arrays
> Numpy format

- README.md
- cli/__init__.py
- cli/create.py
- cli/execute.py
- cli/main.py
- cli/pyramid.py
- cli/serve.py
- mapchete/commons.py
- mapchete/config_utils.py
- mapchete/core.py
- mapchete/io_utils/formats.py
- setup.py
- static/mapchete_template.mapchete
- static/process_template.py
This PR combines ``mapchete_serve``, ``mapchete_execute`` and ``raster2pyramid`` commands into one ``mapchete`` command. It also adds a ``mapchete create`` subcommand, which creates a dummy .mapchete and .py file.
> Command line tool

- mapchete/__init__.py
- mapchete/cli/execute.py
- mapchete/config/__init__.py
- test/all.py
- test/testdata/file_groups.mapchete
introduces iterable groups of input data
> Input data groups

- CHANGELOG.rst
- mapchete/__init__.py
- mapchete/config/__init__.py
- mapchete/config/_parse_input.py
- mapchete/formats/base.py
add optional ``cleanup()`` function for ``InputData`` objects which gets called as soon as ``Mapchete`` is closed.
> Cleanup input data

- mapchete/config/_parse_input.py
- mapchete/formats/default/tile_directory.py
- mapchete/io/raster.py
- mapchete/io/vector.py
- mapchete/tile.py
- setup.py
- test/conftest.py
- test/test_formats_tiledir_input.py
- test/test_io.py
- test/testdata/cleantopo_br_tiledir.mapchete
- test/testdata/cleantopo_remote.mapchete
- test/testdata/geojson_tiledir.mapchete
> Tile directory input

- test/conftest.py
- test/test_cli.py
- test/test_commons.py
- test/test_config.py
- test/test_errors.py
- test/test_formats.py
- test/test_formats_geojson.py
- test/test_formats_geotiff.py
- test/test_formats_png.py
- test/test_formats_png_hillshade.py
- test/test_io.py
- test/test_mapchete.py
now using pytest fixtures for all test data & test configurations to make tests more clear
> Cleanup tests

- .travis.yml
- CHANGELOG.rst
- mapchete/cli/index.py
- mapchete/cli/main.py
- mapchete/formats/base.py
- mapchete/formats/default/geojson.py
- mapchete/formats/default/gtiff.py
- mapchete/formats/default/png.py
- mapchete/formats/default/png_hillshade.py
- mapchete/formats/default/vector_file.py
- mapchete/index.py
- test/test_cli.py
- test/test_formats.py
implemented:
- ``GeoJSON``
- ``GeoPackage``
- ``textfile``
``VRT`` creation requires more effort, unless we want to ``subprocess`` call ``gdalbuildvrt``, therefore this feature is omitted for now.
see issue #107
> CLI index command

- .travis.yml
- setup.py
- use Ubuntu 16.04 for travis
- removed Python 3.4 tests
> Travis xenial

- mapchete/_core.py
Use the more clean `concurrent.futures` way rather than `multiprocessing`
> replace multiprocessing with concurrent.futures

- CHANGELOG.rst
- README.rst
- mapchete/cli/default/serve.py
- mapchete/commons/contours.py
- mapchete/formats/default/geojson.py
- mapchete/formats/default/gtiff.py
- mapchete/formats/default/png.py
- mapchete/formats/default/png_hillshade.py
- mapchete/formats/default/tile_directory.py
- mapchete/io/__init__.py
- requirements.txt
- setup.py
dependencies for certain features are not anymore installed by default:
- contours: matplotlib
- s3: boto3
- serve: flask, werkzeug
> Extra require

- CHANGELOG.rst
- mapchete/io/raster.py
> Transform shape

- CHANGELOG.rst
- mapchete/__init__.py
- mapchete/_core.py
- mapchete/cli/default/processes.py
- mapchete/config.py
- mapchete/formats/__init__.py
- mapchete/log.py
- mapchete/processes/convert.py
- test/test_formats.py
- automatically detect and configure logger from process file
- increase log level for some messages
> Extend logging

- mapchete/tile.py
- requirements.txt
adapt `mapchete.tile` to updated `tilematrix` API
> Tilematrix tile properties

- mapchete/cli/default/create.py
- mapchete/config.py
- mapchete/formats/default/gtiff.py
- requirements.txt
- setup.py
- test/test_config.py
fixes for #181 #182 #167 and #176
> parse input fixes

- CHANGELOG.rst
- mapchete/cli/utils.py
- test/test_cli.py
> use hyphens instead of underscore in CLI options

- CHANGELOG.rst
- mapchete/cli/default/convert.py
- mapchete/processes/convert.py
- test/test_cli.py
- also intersect bounds with clip-geometry
- add --co creation options from rasterio
> `mapchete convert` enhancements (#192)

- CHANGELOG.rst
- mapchete/_core.py
- mapchete/_processing.py
- mapchete/_validate.py
- mapchete/cli/default/convert.py
- mapchete/cli/utils.py
- mapchete/config.py
- mapchete/formats/__init__.py
- mapchete/formats/default/gtiff.py
- mapchete/io/__init__.py
- mapchete/io/raster.py
- mapchete/io/vector.py
- test/test_cli.py
- test/test_deprecated.py
- test/test_errors.py
- test/test_formats_geotiff.py
- test/test_mapchete.py
- test/test_timer.py
> Check existing tiles before

- CHANGELOG.rst
- mapchete/_processing.py
- mapchete/cli/default/processes.py
- mapchete/io/raster.py
* fixed raise of ``FileNotFounderror`` on ``mapchete.io.raster.read_raster_no_crs()``
* fixed overview ``get_parent()`` on zoom 0 in batch processing
* sort processes alphabetically in ``mapchete processes``
> Minor fixes

- mapchete/_processing.py
- mapchete/commons/hillshade.py
- mapchete/formats/base.py
- mapchete/formats/default/gtiff.py
- mapchete/formats/default/png.py
- mapchete/formats/default/png_hillshade.py
- mapchete/index.py
> read output nodata value from within a process

- mapchete/io/_misc.py
- mapchete/io/raster.py
- add GDAL HTTP options
- handle `AccessDenied` exception which could occur if after an `RasterioIOError` a check is run if the file even exists
> remote reading fixes

- CHANGELOG.rst
- mapchete/_processing.py
- mapchete/cli/default/convert.py
- mapchete/cli/utils.py
- mapchete/commons/clip.py
- mapchete/processes/convert.py
- test/test_cli.py
> mapchete convert add overviews option

- CHANGELOG.rst
- doc/source/apidoc/mapchete.rst
- doc/source/apidoc/mapchete.validate.rst
- mapchete/_processing.py
- mapchete/formats/default/gtiff.py
- mapchete/io/raster.py
- test/conftest.py
- test/test_io.py
- test/test_mapchete.py
- test/testdata/baselevels_custom_nodata.mapchete
> fix custom nodata values in overviews

- .travis.yml
- README.rst
- doc/source/apidoc/mapchete.processes.contours.rst
- doc/source/apidoc/mapchete.processes.hillshade.rst
- doc/source/apidoc/mapchete.processes.rst
- doc/source/installation.rst
> let travis also build shapely from source

- mapchete/config.py
- test/test_config.py
- test/test_mapchete.py
…don't initialize inputs on readonly mode;
> only initialize inputs if necessary

- .travis.yml
- requirements.txt
- setup.py
- test/test_cli.py
* travis: use `--upgrade` flag when installing testing dependencies
* increase click dependency to >=7.1.1
> Fix failing tests (#253)

- mapchete/io/_path.py
> update indexes on remote TileDirectories

- mapchete/_core.py
- mapchete/cli/default/cp.py
- mapchete/cli/default/index.py
- mapchete/cli/utils.py
- mapchete/config.py
- mapchete/index.py
- test/test_cli.py
> enable index command to accept tile directories

- mapchete/_processing.py
- mapchete/io/_misc.py
- mapchete/io/raster.py
> optimize GDAL options on remote files

- mapchete/errors.py
- mapchete/io/raster.py
- mapchete/io/vector.py
- test/test_io.py
> raise generic MapcheteIOError on read fails

- mapchete/formats/default/geojson.py
- mapchete/io/_geometry_operations.py
- mapchete/io/_path.py
- mapchete/io/vector.py
- test/test_formats_geojson.py
- test/test_io.py
> allow multipart geometries

- setup.py
* fix #299 
* also move werkzeug dependency to `serve` extra
> don't parse requirements.txt in setup.py

- mapchete/io/_path.py
- setup.py
* set 0.5.1 as minimum version for s3fs
* handle s3 check if fs.protocol returns a list
> fix s3fs usage & required version

- mapchete/formats/default/gtiff.py
set new defaults:
* compression: deflate
* blocksize: 512
> adapt default GTiff profile

- mapchete/config.py
- mapchete/formats/default/gtiff.py
- mapchete/io/raster.py
- test/conftest.py
- test/test_cli.py
- test/test_config.py
- test/test_deprecated.py
- test/test_errors.py
- test/test_formats.py
- test/test_formats_geotiff.py
- test/test_io.py
- test/test_log.py
> handle and fix warnings

- .github/workflows/python-package.yml
- mapchete/formats/default/_fiona_base.py
- mapchete/formats/default/flatgeobuf.py
- mapchete/formats/default/geojson.py
- mapchete/io/_geometry_operations.py
- mapchete/io/vector.py
- setup.py
- test/conftest.py
- test/test_formats_flatgeobuf.py
- test/testdata/flatgeobuf.mapchete
fixes #320 
- add tiled FlatGeobuf output driver
- enables "Unknown" geometry type for GeoJSON driver to allow mixing of various geometry types
> add tiled FlatGeobuf output driver

- mapchete/processes/convert.py
> print user warning if deprecated input name is used

- mapchete/_processing.py
- mapchete/formats/default/gtiff.py
- test/test_cli.py
- test/test_formats_geotiff.py
> Fix single GTiff overview creation

- mapchete/_executor.py
- mapchete/_processing.py
- mapchete/commands/_convert.py
- mapchete/commands/_cp.py
- mapchete/commands/_execute.py
- mapchete/commands/_index.py
- mapchete/commands/_rm.py
- mapchete/tile.py
> add preprocessing and tiles count to Job

- mapchete/_executor.py
immediately get future result, hopefully not blocking yielding future results from batches anymore
> let as_completed fetch future results

- mapchete/io/_misc.py
- requirements.txt
- test/test_io.py
adapt tests to be more tolerant towards newer proj versions; remove rasterio max version
> fix support for proj 8.2.0

- mapchete/_executor.py
- mapchete/_processing.py
- mapchete/_tasks.py
- mapchete/cli/default/execute.py
- mapchete/commands/_execute.py
* fix `continue` mode for task graph
* don't raise exception if scheduler exits while waiting for tasks to finish
* fix running tasks count for `DaskExecutor.as_completed`
> Dask executor fixes

- mapchete/_executor.py
> reduce executor log level

- mapchete/_executor.py
- mapchete/_processing.py
- mapchete/_tasks.py
- mapchete/errors.py
- mapchete/processes/hillshade.py
- test/test_errors.py
- test/test_executor.py
> Fix 464 add failed task information

- mapchete/formats/default/gtiff.py
> force blocksize being int

- .github/workflows/python-package.yml
- mapchete/formats/default/_fiona_base.py
- mapchete/formats/default/png.py
- mapchete/formats/default/png_hillshade.py
- mapchete/index.py
- mapchete/io/_geometry_operations.py
- mapchete/io/_json.py
- mapchete/io/_misc.py
- mapchete/io/raster.py
- mapchete/io/vector.py
- pyproject.toml
- requirements.txt
- test/test_index.py
- test/test_io_raster.py
- test/test_io_vector.py
- test/test_mapchete.py
> fix failing tests due to s3fs update

- pyproject.toml
... as it does not yet implement STAC version 1.0
> pin pystac version to 1.7.3

- mapchete/_core.py
- mapchete/stac.py
- pyproject.toml
- test/test_stac.py
> update stacta file schema to STAC 1.0.0; apply hack for GDAL

- mapchete/io/raster.py
- mapchete/path.py
- test/conftest.py
- test/test_io_raster.py
- test/test_path.py
* added `ReferencedRaster.to_file()`
* added `read_raster(tile=...)` kwarg to resample incoming raster
> ReferencedRaster feature

- pyproject.toml
- requirements.txt
> require Shapely>=2.0.0

- mapchete/path.py
- mapchete/settings.py
- test/test_io.py
- test/test_processing_base.py
> fix tiles exist check on output tiles smaller than process tiles

- mapchete/geometry/repair.py
- mapchete/geometry/reproject.py
- mapchete/geometry/segmentize.py
* make check for known CRSes to determine their bounds more solid
* fix code smells
> adapt to new rasterio.crs.CRS behavior

- mapchete/config/process_func.py
- mapchete/executor/base.py
- mapchete/executor/concurrent_futures.py
- mapchete/executor/dask.py
- mapchete/executor/future.py
- mapchete/executor/sequential.py
- mapchete/executor/types.py
- mapchete/geometry/reproject.py
- mapchete/geometry/transform.py
- mapchete/io/raster/mosaic.py
- mapchete/io/raster/read.py
- mapchete/io/raster/referenced_raster.py
- mapchete/processing/base.py
- mapchete/processing/tasks.py
- mapchete/settings.py
- mapchete/stac.py
- test/commands/test_execute.py
- test/conftest.py
- test/executor/test_base.py
- test/executor/test_concurrent_futures.py
- test/executor/test_dask.py
- test/executor/test_future.py
- test/geometry/test_reproject.py
- test/io/raster/test_read.py
- test/test_examples.py
- test/test_formats_tiledir_input.py
- test/test_preprocessing.py
- test/test_processing_base.py
* core
* `config.process_func.ProcessFunc`: fix `FileExistsError` sometimes occuring when using multiprocessing
* `executor`: add proper typing and completely refactor `as_completed()` methods for all executors.
* `executor.concurrent_futures.ConcurrentFuturesExecutor.map()`: actually implement concurrency
* `geometry.reproject.reproject_geometry()`: add `engine` kwarg and implement `pyproj` transform (now default) alongside existing `fiona` which makes reprojecting much faster. Behavior can be configured using the `MAPCHETE_REPROJECT_GEOMETRY_ENGINE` environment variable ("pyproj" or "fiona")
* `io.raster`: fix typing smells in module
* tests
* restructure tests for `executor` submodule
* make all processing related tests faster by properly reusing executor fixtures and reprojection …
> some executor updates

- examples/custom_tile_size/custom_tile_size.mapchete
- mapchete/commands/convert.py
- mapchete/config/base.py
- mapchete/config/models.py
- mapchete/config/parse.py
- mapchete/formats/base.py
- mapchete/io/_misc.py
- mapchete/tile.py
- test/cli/default/__init__.py
- test/conftest.py
- test/test_examples.py
> make sure 'tile_size' parameter is propagated from configuration

- examples/special_kwargs/process.py
- examples/special_kwargs/special_kwargs.mapchete
- mapchete/__init__.py
- mapchete/config/base.py
- mapchete/config/process_func.py
- mapchete/executor/future.py
- mapchete/geometry/filter.py
- mapchete/process_func_special_types.py
- mapchete/processing/execute.py
- mapchete/processing/tasks.py
- test/conftest.py
- test/test_examples.py
* fix filter for multipart geometries
* add special function kwargs 'tile', 'process_pixelbuffer' and 'output_pixelbuffer' to make them available within execute() if desired
* `MFuture`: add name to repr string
> Fix multipart filter

- .github/workflows/python-package.yml
- mapchete/cli/mapchete/stac.py
- mapchete/processing/base.py
- mapchete/stac.py
- pyproject.toml
- test/conftest.py
- test/test_stac.py
- test/testdata/stac/eoxcloudless-viewing-basic-dummy.json
- test/testdata/stac/eoxcloudless-viewing-basic-rel-paths-dummy.json
> fix stac create-item relative paths json generation for self href of STACTA .json
