mapchete/mapchete

CHANGELOG.rst, mapchete/__init__.py, mapchete/config/__init__.py, mapchete/config/_parse_input.py, mapchete/errors.py, mapchete/formats/__init__.py, mapchete/io/vector.py, setup.py, test/test_config.py, test/test_formats.py, test/test_io.py, test/testdata/abstract_input.mapchete
Using ``input_files`` now raises a deprecation warning.
``input`` works the same way as ``input_files`` but enables the development of additional drivers which require more parameters than just a file path (e.g. db connections etc). These "abstract" input types just require a ``format`` parameter for the driver name.
closing #66
=> Files input

CHANGELOG.rst, mapchete/__init__.py, mapchete/_batch.py, mapchete/cli/serve.py, mapchete/errors.py, mapchete/formats/default/geojson.py, mapchete/formats/default/gtiff.py, mapchete/formats/default/png.py, mapchete/formats/default/png_hillshade.py, mapchete/io/raster.py, mapchete/io/vector.py, mapchete/tile.py, test/test_config.py, test/test_formats.py, test/test_formats_geojson.py, test/test_formats_geotiff.py, test/test_formats_png.py, test/test_formats_png_hillshade.py, test/test_io.py, test/test_mapchete.py
* better memory handling by detatching process output data from ``BufferedTile`` objects
* breaking API changes:
* Mapchete.execute() returns raw data instead of tile with data attribute
* Mapchete.read() returns raw data instead of tile with data attribute
* Mapchete.get_raw_output() returns raw data instead of tile with data attribute
* Mapchete.write() requires process_tile and data as arguments
* same valid for all other read() and write() functions in drivers & MapcheteProcess object
* new MapcheteNodataTile exception to indicate an empty process output
=> Detatch tile data

CHANGELOG.rst, mapchete/__init__.py, mapchete/_core.py, mapchete/config.py, requirements.txt, setup.py, test/test_config.py, test/test_deprecated.py, test/test_mapchete.py
Added `effective_bounds` to configuration which resizes bounds to tile grid. This is important for some input drivers which need to initialize with the real bounds (= including all process tiles).
=> Snap bounds to zoom

CHANGELOG.rst, README.rst, mapchete/__init__.py, mapchete/cli/default/execute.py, mapchete/cli/default/index.py, mapchete/cli/utils.py, mapchete/index.py, mapchete/io/__init__.py, mapchete/io/raster.py, mapchete/tile.py, requirements.txt, setup.py, test/test_cli.py, test/test_index.py
* enable VRT creation for indexes
* added ``--vrt`` flag and ``--idx_out_dir`` option to ``mapchete execute``
* renamed ``--out_dir`` to ``--idx_out_dir`` for ``mapchete index``
* ``BufferedTile`` shape (``height``, ``width``) and bounds (``left``, ``bottom``, ``right`` and ``top``) properties now return correct values
* ``BufferedTile.shape`` now follows the order ``(height, width)`` (update from ``tilematrix 0.18``)
closing #110
=> enable VRT indexes

CHANGELOG.rst, mapchete/__init__.py, mapchete/formats/default/tile_directory.py, mapchete/io/__init__.py, mapchete/io/raster.py, mapchete/io/vector.py, test/conftest.py, test/test_formats_tiledir_input.py, test/test_io.py, test/test_mapchete.py, test/testdata/cleantopo_br_mercator.mapchete
* `mapchete` outputs in a different CRS can now be opened as input of another process; various options of selecting the appropriate grid (i.e. zoom level) can be used
* `read_raster_window()` and `read_vector_window()` functions accept multiple paths and can now be used to merge outputs
* `mapchete.io` package has `tile_to_zoom_level()` function which can determine the appropriate zoom level of a tile pyramid in a different CRS
PR closes #71
=> Tiledata dir reproject

CHANGELOG.rst, mapchete/formats/default/raster_file.py, mapchete/formats/default/tile_directory.py, mapchete/formats/default/vector_file.py, mapchete/processes/convert.py, setup.py, test/test_processes.py
- added ``mapchete.processes.convert``
- move resampling kwarg to ``open()`` instead of ``read()`` for tile directory
=> convert default process

CHANGELOG.rst, mapchete/_core.py, mapchete/errors.py, mapchete/io/vector.py, mapchete/log.py, test/test_io.py
* ``clean_geometry_type()`` raises ``GeometryTypeError`` if types do not match instead of
returning ``None``
* quietly handle ``GeometryTypeError`` when reading and reprojecting vector data
* default log level now is ``logging.WARNIGN``, not ``logging.ERROR``
=> Geometry reprojection

mapchete/cli/default/serve.py, mapchete/config.py, mapchete/formats/__init__.py, mapchete/formats/base.py, mapchete/formats/default/geojson.py, mapchete/formats/default/gtiff.py, mapchete/formats/default/mapchete_input.py, mapchete/formats/default/png.py, mapchete/formats/default/png_hillshade.py, mapchete/formats/default/raster_file.py, mapchete/formats/default/tile_directory.py, mapchete/formats/default/vector_file.py, mapchete/io/__init__.py, mapchete/log.py, mapchete/tile.py, test/conftest.py, test/test_formats.py, test/test_formats_geojson.py, test/test_formats_geotiff.py, test/test_formats_png.py, test/test_formats_png_hillshade.py, test/test_formats_tiledir_input.py, test/testdata/cleantopo_br_tiledir.mapchete, test/testdata/cleantopo_remote.mapchete, test/testdata/deprecated_params.mapchete, test/testdata/geojson.mapchete, test/testdata/geojson_tiledir.mapchete, test/testdata/old_geodetic_shape_metadata.json, test/testdata/old_style_metadata.json
- `TileDirectory` input can now handle custom grids
- use `tilematrix` `to_dict()` and `from_dict()` functions to dump & load `TilePyramid` configurations
- properly use `DeprecationWarning` in `warnings.warn()` calls
- move `params_to_dump()`, `read_output_metadata()` and `write_output_metadata()` from `io` to `formats`
=> Tiledir custom grid

mapchete/config.py
=> load inputs as readonly if only overviews are going to be built

mapchete/cli/default/convert.py, test/test_cli.py
=> use os.path.splitext to guess whether path is a file or a directory

CHANGELOG.rst, mapchete/cli/default/processes.py, mapchete/processes/__init__.py
=> don't raise exception when one of the processes cannot be imported

mapchete/config.py
In readonly mode all init_bounds (e.g. through the --bounds parameter) are ignored and the default process pyramid bounds are used. This results in the inability to spatially subset the process area.
=> use init_bounds instead of pyramid bounds on readonly mode

mapchete/_registered.py, mapchete/cli/default/create.py, mapchete/cli/main.py, mapchete/formats/__init__.py, mapchete/log.py, mapchete/processes/__init__.py, requirements.txt, setup.py
This aims to speed up loading additional drivers, CLI commands and processes which currently use the `pkg_resources` module which can be replaced by the faster `importlib-metadata` and
`importlib-resources` modules.
More details can be found on this [`setuptools` issue](https://github.com/pypa/setuptools/issues/510).
Still improvements can be made as it seems importing `rasterio` takes ~400ms alone.
=> speed up extension loading

mapchete/_core.py, mapchete/index.py, mapchete/io/__init__.py, mapchete/io/_path.py, mapchete/log.py
=> use boto paging to check multiple tiles at once (#264)

mapchete/config.py, mapchete/formats/default/mapchete_input.py, test/test_config.py
* fix non-overlapping bounds if provided as extra kwarg
* don't pass on init bounds to mapchete input
=> bounds fix

.github/workflows/python-package.yml, mapchete/formats/default/tile_directory.py, mapchete/io/_geometry_operations.py, mapchete/io/raster.py, requirements.txt, setup.py
* add `pyproj` to dependencies
* `mapchete.io.vector.reproject_geometry()`:
* use `pyproj` to determine CRS bounds to clip geometries when reprojecting
* enable geometry segmentation before geometry is clipped (`segmentize_on_clip=False` and `segmentize_fraction=100` args)
* suppress `rasterio` warnings when reading rasters (too many `rasterio.errors.NodataShadowWarning`s)
=> introduce pyproj to enable CRS bounds clip to other CRSes

mapchete/_core.py, mapchete/_executor.py, mapchete/_processing.py, test/test_executor.py
* let Executor keep track of running futures and remove finished ones to save memory; try to yield finished futures while submitting new tasks to Executor
* also submit single tile tasks to dask if available
=> WIP: Executor memory usage

mapchete/_executor.py, test/test_executor.py, test/test_formats_geotiff.py
* make sure Executor.running_futures is cleared after earh as_completed() and cancel() call
* skip COG tests if driver is not available in GDAL
=> loitering futures & COG tests fix

mapchete/_executor.py, mapchete/errors.py
* use timeouts when calling future.result() or future.exception()
* retry futures failing with timeouts
=> make dask executor more resilient

.github/workflows/python-package.yml, mapchete/io/raster.py, mapchete/io/vector.py, requirements.txt, setup.py
=> exclude vulnerable rasterio dependency

requirements.txt, setup.py
=> add python-dateutil to package requirements

mapchete/_executor.py, mapchete/_processing.py, mapchete/cli/default/stac.py
fall back on reasonable default values of chunksize and max_submitted_tasks; make sure max_submitted_tasks and chunksize are passed on process batches
=> dask chunksize and max_submitted_tasks fix

mapchete/cli/default/cp.py
=> use threaded concurrency on default when calling 'mapchete cp'

doc/source/process_input.rst, mapchete/formats/default/tile_directory.py, test/conftest.py, test/test_formats_tiledir_input.py, test/testdata/cleantopo_read_lower_zoom.mapchete
This PR allows setting default read values to a TileDirectory:
```yaml
input:
file1:
format: TileDirectory
path: cleantopo/
max_zoom: 1
resampling: bilinear
```
In that example, a process running on zoom 2 or higher resamples zoom 1 data from the TileDirectory using bilinear resampling.
=> enable adding default read parameters to TileDirectory input

pyproject.toml, pytest.ini, requirements.txt, test/test_cli.py, test/test_commands.py, test/test_formats.py, test/test_formats_flatgeobuf.py, test/test_formats_geobuf.py, test/test_formats_geojson.py, test/test_formats_geotiff.py, test/test_formats_png.py, test/test_formats_png_hillshade.py, test/test_index.py, test/test_io.py, test/test_io_raster.py, test/test_io_vector.py, test/test_path.py
to better include/exclude tests requiring a special setup
=> add pytest markers 'integration' and 'aws_s3'

mapchete/io/raster/array.py, test/test_io_raster.py
* maybe this, or try to pass `ma.MaskedArray` to the `rasterio.warp.reproject` but seems to work funky now
=> rasterio>=1.4.x reproject array type

mapchete/cli/default/serve.py
The Content-Type header isn't set when out_data is a MemoryFile because of the early return. I don't see why an early return is necessary so I made the branch like the other branches.
=> Fix Content-Type of MemoryFile tiles

mapchete/commands/execute.py, mapchete/executor/__init__.py, mapchete/executor/base.py, mapchete/processing/base.py, mapchete/settings.py, test/executor/test_base.py
closes #653 
* `commands.execute.execute()`: add `retry_delay` option
* fix typing smells around executor classes
=> add retry delay to execute
